# Generated by Django 3.1.1 on 2020-09-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedata',
            name='Data_entry',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagedata',
            name='Followers_count',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagedata',
            name='Follows_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagedata',
            name='Media_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
