# Generated by Django 3.1.1 on 2020-09-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200927_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Male', models.IntegerField()),
                ('Female', models.IntegerField()),
            ],
        ),
    ]
